update(ci): include all modules in SNAP installer by using API calls to bypass downstream limit of 5 projects

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -35,6 +35,16 @@ variables:
     options:
     - "true"
     - "false"
+  # Trigger pipelines via API for the following projects to bypass downstream multiproject trigger limited to 5 projects
+  GITLAB_API_URL: "https://gitlab.com/api/v4"
+  PROJECT_ENGINE: '{"ID" : "42613488", "TOKEN" : "$TRIGGER_TOKEN_ENGINE"}'
+  PROJECT_DESKTOP: '{"ID" : "42613585", "TOKEN" : "$TRIGGER_TOKEN_DESKTOP"}'
+  PROJECTS: '[
+      {"ID" : "45963970", "TOKEN" : "$TRIGGER_TOKEN_MICROWAVE"}, 
+      {"ID" : "45964007", "TOKEN" : "$TRIGGER_TOKEN_OPTICAL"},
+      {"ID" : "46471532", "TOKEN" : "$TRIGGER_TOKEN_ESA_SNAPPY"},
+      {"ID" : "44112186", "TOKEN" : "$TRIGGER_TOKEN_SMOS_BOX"}
+    ]'
 
 stages:
   - compile
@@ -61,36 +71,188 @@ stages:
 
 compile-snap-engine:
   extends: .compile
-  trigger: 
-    project: senbox-org/snap-engine
-    branch: $COMPILE_BRANCH
-    strategy: depend
+  image: alpine
+  before_script:
+    - apk add --no-cache curl
+    - apk add --no-cache jq
+    - mkdir -p artifacts
+  script:    
+    - |
+      PROJECT_ID=$(echo "$PROJECT_ENGINE" | jq -r '.ID')
+      TOKEN=$(echo "$PROJECT_ENGINE" | jq -r '.TOKEN')      
+      RESPONSE=$(curl -X POST --fail -F token=$TOKEN -F ref=$COMPILE_BRANCH https://gitlab.com/api/v4/projects/$PROJECT_ID/trigger/pipeline)
+      echo "RESPONSE $RESPONSE"
+      PIPELINE_ID=$(echo "$RESPONSE" | jq -r '.id')
+      echo "Triggered pipeline $PIPELINE_ID for project $PROJECT_ID"
+      while true; do        
+        echo "Checking pipeline $PIPELINE_ID for project $PROJECT_ID..."
+        STATUS=$(curl --silent --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$GITLAB_API_URL/projects/$PROJECT_ID/pipelines/$PIPELINE_ID" | jq -r '.status')
+        echo "Pipeline $PIPELINE_ID status: $STATUS"
+        if [[ "$STATUS" == "success" ]]; then
+          echo "Pipeline $PIPELINE_ID completed successfully!"
+          break          
+        elif [[ "$STATUS" == "failed" || "$STATUS" == "canceled" ]]; then
+          echo "Pipeline $PIPELINE_ID failed or was canceled!"
+          exit 1
+        fi
+        sleep 30     
+      done
+      echo "Fetching job list for pipeline $PIPELINE_ID in project $PROJECT_ID..."
+      JOB_ID=$(curl --silent --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$GITLAB_API_URL/projects/$PROJECT_ID/pipelines/$PIPELINE_ID/jobs" | jq -r '.[] | select(.name=="mvn-build" and .status=="success") | .id' | head -n 1)
+      echo "Downloading artifacts from job $JOB_ID in project $PROJECT_ID..."
+      curl --silent --location --output "artifacts_$PROJECT_ID.zip" --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$GITLAB_API_URL/projects/$PROJECT_ID/jobs/$JOB_ID/artifacts"
+      unzip artifacts_$PROJECT_ID.zip "etc/*" -d artifacts
+      unzip artifacts_$PROJECT_ID.zip "LICENSE.html" -d artifacts
+      rm artifacts_$PROJECT_ID.zip
+  artifacts:
+    paths:
+      - artifacts/**
 
 compile-snap-desktop:
   extends: .compile
-  trigger: 
-    project: senbox-org/snap-desktop
-    branch: $COMPILE_BRANCH
-    strategy: depend
+  image: alpine
+  before_script:
+    - apk add --no-cache curl
+    - apk add --no-cache jq
+    - mkdir -p artifacts
+  script:    
+    - |
+      PROJECT_ID=$(echo "$PROJECT_DESKTOP" | jq -r '.ID')
+      TOKEN=$(echo "$PROJECT_DESKTOP" | jq -r '.TOKEN')      
+      RESPONSE=$(curl -X POST --fail -F token=$TOKEN -F ref=$COMPILE_BRANCH https://gitlab.com/api/v4/projects/$PROJECT_ID/trigger/pipeline)
+      echo "RESPONSE $RESPONSE"
+      PIPELINE_ID=$(echo "$RESPONSE" | jq -r '.id')
+      echo "Triggered pipeline $PIPELINE_ID for project $PROJECT_ID"
+      while true; do        
+        echo "Checking pipeline $PIPELINE_ID for project $PROJECT_ID..."
+        STATUS=$(curl --silent --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$GITLAB_API_URL/projects/$PROJECT_ID/pipelines/$PIPELINE_ID" | jq -r '.status')
+        echo "Pipeline $PIPELINE_ID status: $STATUS"
+        if [[ "$STATUS" == "success" ]]; then
+          echo "Pipeline $PIPELINE_ID completed successfully!"
+          break          
+        elif [[ "$STATUS" == "failed" || "$STATUS" == "canceled" ]]; then
+          echo "Pipeline $PIPELINE_ID failed or was canceled!"
+          exit 1
+        fi
+        sleep 30     
+      done
+      echo "Fetching job list for pipeline $PIPELINE_ID in project $PROJECT_ID..."
+      JOB_ID=$(curl --silent --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$GITLAB_API_URL/projects/$PROJECT_ID/pipelines/$PIPELINE_ID/jobs" | jq -r '.[] | select(.name=="mvn-build" and .status=="success") | .id' | head -n 1)
+      echo "Downloading artifacts from job $JOB_ID in project $PROJECT_ID..."
+      curl --silent --location --output "artifacts_$PROJECT_ID.zip" --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$GITLAB_API_URL/projects/$PROJECT_ID/jobs/$JOB_ID/artifacts"
+      unzip artifacts_$PROJECT_ID.zip "snap-application/target/*" -d artifacts
+      unzip artifacts_$PROJECT_ID.zip "snap-main/target/*" -d artifacts
+      unzip artifacts_$PROJECT_ID.zip "snap-smart-configurator-ui/src/main/resources/org/esa/snap/smart/configurator/ui/Performance32.png" -d artifacts
+      rm artifacts_$PROJECT_ID.zip
   needs:
-    - job: compile-snap-engine
+    - job: compile-snap-engine    
+  artifacts:
+    paths:
+      - artifacts/**
 
-# Trigger child pipelines to get mvn-build artifacts available (optional, but needed when they have expired)
-compile-others:
+compile-others-trigger-pipelines:
   extends: .compile
-  trigger: 
-    project: $PROJECT
-    branch: $COMPILE_BRANCH
-    strategy: depend
-  parallel:
-    matrix:      
-      - PROJECT: senbox-org/microwave-toolbox
-      - PROJECT: senbox-org/optical-toolbox
-      # - PROJECT: senbox-org/smos-box
-      - PROJECT: senbox-org/esa-snappy
+  image: alpine
+  before_script:
+    - apk add --no-cache curl
+    - apk add --no-cache jq
+  script:
+    - echo "Triggering pipelines for projects $PROJECT_IDS"
+    - |
+      for item in $(echo "$PROJECTS" | jq -c '.[]'); do
+        PROJECT_ID=$(echo "$item" | jq -r '.ID')
+        TOKEN=$(echo "$item" | jq -r '.TOKEN')
+        RESPONSE=$(curl -X POST --fail -F token=$TOKEN -F ref=$COMPILE_BRANCH https://gitlab.com/api/v4/projects/$PROJECT_ID/trigger/pipeline)
+        echo "RESPONSE $RESPONSE"
+        PIPELINE_ID=$(echo "$RESPONSE" | jq -r '.id')
+        echo "Triggered pipeline $PIPELINE_ID for project $PROJECT_ID"
+        echo "$PROJECT_ID=$PIPELINE_ID" >> pipeline.env
+      done
   needs:
     - job: compile-snap-engine
     - job: compile-snap-desktop
+  artifacts:
+    paths:
+      - pipeline.env
+
+compile-others-wait-for-pipelines:
+  extends: .compile
+  image: alpine
+  before_script:
+    - apk add --no-cache curl
+    - apk add --no-cache jq
+  script:
+    - echo "Waiting for pipelines to finish..."
+    - |
+      while true; do
+        FINISHED=0        
+        for item in $(echo "$PROJECTS" | jq -c '.[]'); do
+          PROJECT_ID=$(echo "$item" | jq -r '.ID')
+          PIPELINE_ID=$(grep "$PROJECT_ID=" pipeline.env | cut -d '=' -f2)
+          echo "Checking pipeline $PIPELINE_ID for project $PROJECT_ID..."
+          STATUS=$(curl --silent --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$GITLAB_API_URL/projects/$PROJECT_ID/pipelines/$PIPELINE_ID" | jq -r '.status')
+          echo "Pipeline $PIPELINE_ID status: $STATUS"
+          if [[ "$STATUS" == "success" ]]; then
+            echo "Pipeline $PIPELINE_ID completed successfully!"
+            FINISHED=$(($FINISHED + 1))
+          elif [[ "$STATUS" == "failed" || "$STATUS" == "canceled" ]]; then
+            echo "Pipeline $PIPELINE_ID failed or was canceled!"
+            exit 1
+          fi          
+        done
+        PROJECTS_COUNT=$(echo "$PROJECTS" | jq 'length')
+        echo "Projects: $PROJECTS_COUNT"
+        echo "Finished: $FINISHED"
+        if [ $FINISHED -eq $PROJECTS_COUNT ]; then 
+          break
+        else        
+          sleep 30
+        fi
+      done
+  needs:
+    - job: compile-others-trigger-pipelines
+  artifacts:
+    paths:
+      - pipeline.env
+
+compile-others-fetch-artifacts:
+  extends: .compile
+  image: alpine
+  before_script:
+    - apk add --no-cache curl
+    - apk add --no-cache jq
+    - mkdir -p artifacts
+  script:
+    - |
+      for item in $(echo "$PROJECTS" | jq -c '.[]'); do
+        PROJECT_ID=$(echo "$item" | jq -r '.ID')
+        TOKEN=$(echo "$item" | jq -r '.TOKEN')
+        PIPELINE_ID=$(grep "$PROJECT_ID=" pipeline.env | cut -d '=' -f2)
+        echo "Fetching job list for pipeline $PIPELINE_ID in project $PROJECT_ID..."
+        JOB_ID=$(curl --silent --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$GITLAB_API_URL/projects/$PROJECT_ID/pipelines/$PIPELINE_ID/jobs" | jq -r '.[] | select(.name=="mvn-build" and .status=="success") | .id' | head -n 1)
+        echo "Downloading artifacts from job $JOB_ID in project $PROJECT_ID..."
+        curl --silent --location --output "artifacts_$PROJECT_ID.zip" --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$GITLAB_API_URL/projects/$PROJECT_ID/jobs/$JOB_ID/artifacts"
+        if [[ "$TOKEN" == "$TRIGGER_TOKEN_MICROWAVE" ]]; then
+          unzip artifacts_$PROJECT_ID.zip "microwavetbx-kit/target/netbeans_clusters/microwavetbx/*" -d artifacts
+          unzip artifacts_$PROJECT_ID.zip "microwavetbx-kit/target/netbeans_clusters/rstb/*" -d artifacts
+        fi
+        if [[ "$TOKEN" == "$TRIGGER_TOKEN_OPTICAL" ]]; then
+          unzip artifacts_$PROJECT_ID.zip "opttbx-kit/target/netbeans_clusters/opttbx/*" -d artifacts          
+        fi
+        if [[ "$TOKEN" == "$TRIGGER_TOKEN_ESA_SNAPPY" ]]; then
+          unzip artifacts_$PROJECT_ID.zip "esasnappy-kit/target/nbm/clusters/extra/*" -d artifacts          
+        fi
+        if [[ "$TOKEN" == "$TRIGGER_TOKEN_SMOS_BOX" ]]; then
+          unzip artifacts_$PROJECT_ID.zip "smos-kit/target/netbeans_clusters/*" -d artifacts          
+        fi
+        rm artifacts_$PROJECT_ID.zip
+      done
+  needs:
+    - job: compile-others-wait-for-pipelines
+  artifacts:
+    expire_in: 2 hours
+    paths:
+      - artifacts/**
 
 # Fetch artifacts built at compile stage
 build:
@@ -115,30 +277,13 @@ build:
     when: always
   - when: on_success
   needs:
-    - job: compile-others
-      optional: true
-    - project: senbox-org/snap-engine
-      job: mvn-build
-      ref: $COMPILE_BRANCH
-      artifacts: true
-    - project: senbox-org/snap-desktop
-      job: mvn-build
-      ref: $COMPILE_BRANCH
-      artifacts: true
-    - project: senbox-org/microwave-toolbox
-      job: mvn-build
-      ref: $COMPILE_BRANCH
-      artifacts: true
-    - project: senbox-org/optical-toolbox
-      job: mvn-build
-      ref: $COMPILE_BRANCH
-      artifacts: true
-    # - project: senbox-org/smos-box
-    - project: senbox-org/esa-snappy
-      job: mvn-build
-      ref: $COMPILE_BRANCH
-      artifacts: true
-  script: echo build-snap
+    - job: compile-snap-engine
+    - job: compile-snap-desktop
+    - job: compile-others-fetch-artifacts
+  script: 
+    - | 
+      mv artifacts/* .
+      rmdir artifacts
   artifacts:
     expire_in: 2 hours
     paths:
@@ -150,7 +295,7 @@ build:
       - "${CI_PROJECT_DIR}/microwavetbx-kit/target/netbeans_clusters/microwavetbx"
       - "${CI_PROJECT_DIR}/microwavetbx-kit/target/netbeans_clusters/rstb"
       - "${CI_PROJECT_DIR}/opttbx-kit/target/netbeans_clusters/opttbx"
-      # - "${CI_PROJECT_DIR}/smos-kit/target/netbeans_clusters"
+      - "${CI_PROJECT_DIR}/smos-kit/target/netbeans_clusters"
       - "${CI_PROJECT_DIR}/esasnappy-kit/target/nbm/clusters/extra"
 
 # Before building the image we need other projects artifacts  
