update(ci): use API also for engine and desktop

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -35,9 +35,10 @@ variables:
     options:
     - "true"
     - "false"
-  GITLAB_API_URL: "https://gitlab.com/api/v4"
   # Trigger pipelines via API for the following projects to bypass downstream multiproject trigger limited to 5 projects
-  # "45963970 45964007 46471532 44112186" - Microwave, Optical, ESA-Snappy, Smos Box
+  GITLAB_API_URL: "https://gitlab.com/api/v4"
+  PROJECT_ENGINE: '{"ID" : "42613488", "TOKEN" : "$TRIGGER_TOKEN_ENGINE"}'
+  PROJECT_DESKTOP: '{"ID" : "42613585", "TOKEN" : "$TRIGGER_TOKEN_DESKTOP"}'
   PROJECTS: '[
       {"ID" : "45963970", "TOKEN" : "$TRIGGER_TOKEN_MICROWAVE"}, 
       {"ID" : "45964007", "TOKEN" : "$TRIGGER_TOKEN_OPTICAL"},
@@ -68,21 +69,21 @@ stages:
     #   variables:
     #     COMPILE_BRANCH: $CI_COMMIT_TAG
 
-compile-snap-engine:
-  extends: .compile
-  trigger: 
-    project: senbox-org/snap-engine
-    branch: $COMPILE_BRANCH
-    strategy: depend
+# compile-snap-engine:
+#   extends: .compile
+#   trigger: 
+#     project: senbox-org/snap-engine
+#     branch: $COMPILE_BRANCH
+#     strategy: depend
 
-compile-snap-desktop:
-  extends: .compile
-  trigger: 
-    project: senbox-org/snap-desktop
-    branch: $COMPILE_BRANCH
-    strategy: depend
-  needs:
-    - job: compile-snap-engine
+# compile-snap-desktop:
+#   extends: .compile
+#   trigger: 
+#     project: senbox-org/snap-desktop
+#     branch: $COMPILE_BRANCH
+#     strategy: depend
+#   needs:
+#     - job: compile-snap-engine
 
 # Trigger child pipelines to get mvn-build artifacts available (optional, but needed when they have expired)
 # compile-others:
@@ -100,6 +101,87 @@ compile-snap-desktop:
 #   needs:
 #     - job: compile-snap-engine
 #     - job: compile-snap-desktop
+
+compile-snap-engine:
+  extends: .compile
+  image: alpine
+  before_script:
+    - apk add --no-cache curl
+    - apk add --no-cache jq
+    - mkdir artifacts
+  script:    
+    - |
+      PROJECT_ID=$(echo "$PROJECT_ENGINE" | jq -r '.ID')
+      TOKEN=$(echo "$PROJECT_ENGINE" | jq -r '.TOKEN')      
+      RESPONSE=$(curl -X POST --fail -F token=$TOKEN -F ref=$COMPILE_BRANCH https://gitlab.com/api/v4/projects/$PROJECT_ID/trigger/pipeline)
+      echo "RESPONSE $RESPONSE"
+      PIPELINE_ID=$(echo "$RESPONSE" | jq -r '.id')
+      echo "Triggered pipeline $PIPELINE_ID for project $PROJECT_ID"
+      while true; do        
+        echo "Checking pipeline $PIPELINE_ID for project $PROJECT_ID..."
+        STATUS=$(curl --silent --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$GITLAB_API_URL/projects/$PROJECT_ID/pipelines/$PIPELINE_ID" | jq -r '.status')
+        echo "Pipeline $PIPELINE_ID status: $STATUS"
+        if [[ "$STATUS" == "success" ]]; then
+          echo "Pipeline $PIPELINE_ID completed successfully!"
+          break          
+        elif [[ "$STATUS" == "failed" || "$STATUS" == "canceled" ]]; then
+          echo "Pipeline $PIPELINE_ID failed or was canceled!"
+          exit 1
+        fi
+        sleep 30     
+      done
+      echo "Fetching job list for pipeline $PIPELINE_ID in project $PROJECT_ID..."
+      JOB_ID=$(curl --silent --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$GITLAB_API_URL/projects/$PROJECT_ID/pipelines/$PIPELINE_ID/jobs" | jq -r '.[] | select(.name=="mvn-build" and .status=="success") | .id' | head -n 1)
+      echo "Downloading artifacts from job $JOB_ID in project $PROJECT_ID..."
+      curl --silent --location --output "artifacts_$PROJECT_ID.zip" --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$GITLAB_API_URL/projects/$PROJECT_ID/jobs/$JOB_ID/artifacts"
+      unzip artifacts_$PROJECT_ID.zip "etc/*" -d artifacts
+      unzip artifacts_$PROJECT_ID.zip "LICENSE.html" -d artifacts
+      rm artifacts_$PROJECT_ID.zip
+  artifacts:
+    paths:
+      - artifacts/**
+
+compile-snap-desktop:
+  extends: .compile
+  image: alpine
+  before_script:
+    - apk add --no-cache curl
+    - apk add --no-cache jq
+    - mkdir artifacts
+  script:    
+    - |
+      PROJECT_ID=$(echo "$PROJECT_DESKTOP" | jq -r '.ID')
+      TOKEN=$(echo "$PROJECT_DESKTOP" | jq -r '.TOKEN')      
+      RESPONSE=$(curl -X POST --fail -F token=$TOKEN -F ref=$COMPILE_BRANCH https://gitlab.com/api/v4/projects/$PROJECT_ID/trigger/pipeline)
+      echo "RESPONSE $RESPONSE"
+      PIPELINE_ID=$(echo "$RESPONSE" | jq -r '.id')
+      echo "Triggered pipeline $PIPELINE_ID for project $PROJECT_ID"
+      while true; do        
+        echo "Checking pipeline $PIPELINE_ID for project $PROJECT_ID..."
+        STATUS=$(curl --silent --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$GITLAB_API_URL/projects/$PROJECT_ID/pipelines/$PIPELINE_ID" | jq -r '.status')
+        echo "Pipeline $PIPELINE_ID status: $STATUS"
+        if [[ "$STATUS" == "success" ]]; then
+          echo "Pipeline $PIPELINE_ID completed successfully!"
+          break          
+        elif [[ "$STATUS" == "failed" || "$STATUS" == "canceled" ]]; then
+          echo "Pipeline $PIPELINE_ID failed or was canceled!"
+          exit 1
+        fi
+        sleep 30     
+      done
+      echo "Fetching job list for pipeline $PIPELINE_ID in project $PROJECT_ID..."
+      JOB_ID=$(curl --silent --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$GITLAB_API_URL/projects/$PROJECT_ID/pipelines/$PIPELINE_ID/jobs" | jq -r '.[] | select(.name=="mvn-build" and .status=="success") | .id' | head -n 1)
+      echo "Downloading artifacts from job $JOB_ID in project $PROJECT_ID..."
+      curl --silent --location --output "artifacts_$PROJECT_ID.zip" --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$GITLAB_API_URL/projects/$PROJECT_ID/jobs/$JOB_ID/artifacts"
+      unzip artifacts_$PROJECT_ID.zip "snap-application/target/*" -d artifacts
+      unzip artifacts_$PROJECT_ID.zip "snap-main/target/*" -d artifacts
+      unzip artifacts_$PROJECT_ID.zip "snap-smart-configurator-ui/src/main/resources/org/esa/snap/smart/configurator/ui/Performance32.png" -d artifacts
+      rm artifacts_$PROJECT_ID.zip
+  needs:
+    - job: compile-snap-engine    
+  artifacts:
+    paths:
+      - artifacts/**
 
 compile-others-trigger-pipelines:
   extends: .compile
@@ -228,8 +310,13 @@ build:
     when: always
   - when: on_success
   needs:
-    - job: compile-others-fetch-artifacts    
-  script: echo build-snap
+    - job: compile-snap-engine
+    - job: compile-snap-desktop
+    - job: compile-others-fetch-artifacts
+  script: 
+    - | 
+      mv artifacts/* .
+      rmdir artifacts
   artifacts:
     expire_in: 2 hours
     paths:
